import { mediaUrl, money } from "@/lib/api";
import { useEffect, useState } from "react";
import type { Card, Job } from "@/lib/types";

export function Preview({ items, job, busy, pollingPaused, onCheck,
  onRemovePreview, replay, canPreview, onRetryColor }: {
  items: Card[]; job: Job | null; busy: boolean; pollingPaused: boolean;
  onCheck: () => void; onRemovePreview: () => void; replay: boolean; canPreview: boolean;
  onRetryColor: (key: string) => void;
}) {
  const [sampleLoaded, setSampleLoaded] = useState(false);
  const [sampleError, setSampleError] = useState(false);
  const active = job?.status === "running" || job?.status === "queued";
  const referencesReady = replay || items.every(item => item.color_image?.status === "completed");
  const readyCount = replay ? items.length : items.filter(item => item.color_image?.status === "completed").length;
  const [elapsed, setElapsed] = useState(0);
  useEffect(() => {
    if (!active || !job?.created_at) return;
    const update = () => setElapsed(Math.max(0, Math.floor((Date.now() - Date.parse(job.created_at)) / 1000)));
    update();
    const timer = setInterval(update, 1000);
    return () => clearInterval(timer);
  }, [active, job?.created_at]);
  return <div className="preview-block" aria-label="Try-on preview">
    <span className="chat-items-label">Try-on preview</span>
    <div className="preview-refs">
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img className="photo-preview" src={mediaUrl("/api/demo/sample-person.png")} referrerPolicy="no-referrer"
        alt="Fixed AI-generated fictional adult, full-body demo photo"
        onLoad={() => { setSampleLoaded(true); setSampleError(false); }}
        onError={() => { setSampleLoaded(false); setSampleError(true); }} />
      <div>
        <p role="status"><strong>{readyCount} of {items.length} product references ready</strong>{replay ? " · replay bypasses live edits" : ""}.</p>
        <p className="privacy-note">The full-body photo was generated once with AI and is reused for every demo. It is not a real shopper and does not represent you.</p>
        {!referencesReady && <ul className="privacy-note">{items.filter(item => item.color_image?.status !== "completed").map(item =>
          <li key={item.product_id}>{item.name}: {item.color_image?.status || "unavailable"}
            {item.color_image?.status === "failed" && item.color_image.key && item.color_image.error?.retryable &&
              <button className="text-button" disabled={busy || active}
                onClick={() => onRetryColor(item.color_image!.key!)}>Retry this image ↻</button>}</li>)}
          <li>Failed images require an explicit retry; another API charge may apply.</li></ul>}
        <p className="privacy-note">{items.map(item => `${item.name} · ${item.variant.color} / ${item.variant.size} · ${money(item.price_cents)}`).join(" — ")}</p>
      </div>
    </div>
    {sampleError && <p role="alert" className="privacy-note">The fixed demo photo could not be loaded. Refresh the page to retry.</p>}
    <div className="preview-image" aria-live="polite">
      {active && <p role="status">Elapsed: {elapsed}s · completion time varies. You can keep talking while this runs.</p>}
      {job?.status === "completed" && job.image_url ? <>
        {/* Local generated media cannot use a fixed Next remote-image allowlist. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={mediaUrl(job.image_url)} referrerPolicy="no-referrer" alt={job.mode === "fixture" ? "Static replay mannequin diagram, not generated by OpenAI" : job.kind === "try_on" ? "AI-generated photo-based virtual try-on, not a prediction of actual fit" : "AI-generated illustrative concept of the selected outfit"} />
        {job.cached && <strong className="image-badge">Cached image · matching selection</strong>}
        {job.mode === "fixture" && <strong className="image-badge">Replay · static diagram, not GPT-Image output</strong>}
        <p>{job.label}</p>
        {job.kind === "try_on" && <p>Private preview · expires 15 minutes after the request · never shared through the catalog image cache</p>}
      </> : <div className="image-placeholder"><span>{active ? "◌" : "↟"}</span>
        <p>{job?.error?.message || (active ? "Generating in the background. Your selections are safe." : "Visual reference only — no size or fit prediction.")}</p></div>}
    </div>
    <p className="card-cue" role="status">{active ? "Creating your preview…" :
      !canPreview ? "Review your selection with your trail guide before requesting a preview." :
      !referencesReady || !sampleLoaded ? "Waiting for the product and demo-model references to load." :
      job?.status === "failed" ? "Say “try the preview again” in the chat to retry." :
      "Say “show the try-on preview” in the chat to generate it."}</p>
    {replay && <p className="photo-replay">Replay mode: the fixed photo is a pre-generated AI asset, but the try-on result is a static diagram. No live image API call is made.</p>}
    {job && <button className="secondary" disabled={busy} onClick={onRemovePreview}>Remove try-on preview</button>}
    {pollingPaused && <button onClick={onCheck}>Continue checking image status</button>}
    <p className="privacy-note">No new person is generated. Each try-on uses the fixed photo and selected product images in one image edit request. Up to five new image jobs per session. No measurements are inferred. Generated previews are private to this session and expire after 15 minutes. In a real shopping experience, shoppers could upload their own full-body photo, with consent; upload is not enabled in this demo.</p>
  </div>;
}
